version: "2.2"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "127.0.0.1:6831:6831/udp"
      - "127.0.0.1:6832:6832/udp"
      - "127.0.0.1:16686:16686"

  messaging-postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: messaging
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
    ports:
      - "8001:5432"
